trigger:
- main

pool: Default

jobs:
- job: setup
  condition: always()
  displayName: 'Delete old production version'
  steps:
    - script: docker stop pokemon-creator
    - script: docker rm pokemon-creator
    - script: docker rmi $(docker images | grep pokemon-creator | awk '{print $3}')
  
- job: build
  dependsOn: setup
  condition: succeededOrFailed()
  displayName: 'Docker build'
  steps:
    - script: docker build -t pokemon-creator:production .
  

- job: 'Docker run'
  condition: succeeded()
  dependsOn: build
  displayName: 'Docker build'
  steps:
    - script : docker run -d --name pokemon-creator -p 8000:80 pokemon-creator:production
    