trigger:
- main

pool: Default

steps:
- script: docker build -t pokemon-creator:production .
  displayName: 'Docker build'
- script : docker run -d --name pokemon-creator -p 8080:80 pokemon-creator:production
  displayName: 'Docker run'