trigger:
  - none

resources:
  repositories:
    - repository: Tests
      type: github
      ref: main
      name: AlopexMM/qa-pokemon-project
      endpoint: AlopexMM

pool: Default

jobs:
  - job: setup
    condition: always()
    displayName: "Delete old production version"
    steps:
      - script: bash check-container.sh

  - job: build
    dependsOn: setup
    condition: succeeded()
    displayName: "Docker build"
    steps:
      - script: docker build -t pokemon-creator:production .

  - job: run
    condition: succeeded()
    dependsOn: build
    displayName: "Docker run"
    steps:
      - script: docker run -d --name pokemon-creator -p 8000:80 pokemon-creator:production

  - job: tests
    condition: succeeded()
    dependsOn: build
    displayName: "Test webapp"
    steps:
      - checkout: Tests
