services:
  web:
    container_name: web-v1
    build:
      context: ..
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 3000:3000
  backend:
    container_name: backend-v1
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - web
  images:
    container_name: images
    build:
      context: ..
      dockerfile: ./docker/images/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - backend